"""image table

Revision ID: ee6eccd424b4
Revises: 973dca8ba9f2
Create Date: 2024-04-17 22:13:34.823163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ee6eccd424b4'
down_revision: Union[str, None] = '973dca8ba9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
